spring.datasource.url=jdbc:mysql://localhost:3306/edufeedback
spring.datasource.username=root
spring.datasource.password=Amrutha@20006
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin
spring.jpa.hibernate.ddl-auto=update